- id: pyrefly-typecheck
  name: pyrefly check
  entry: pyrefly check
  types_or: [python, pyi]
  language: python
  pass_filenames: false                       # Pyrefly reads config & project roots itself
  args: []
  require_serial: true
  additional_dependencies: []
  minimum_pre_commit_version: "2.9.2"