# pyre.toml

# Let's include everything so commenting out
# project_includes = ["./**/*.py"]

project_excludes = [
  "**/node_modules/**",
  "**/__pycache__/**",
  "**/.git/**",
  "**/venv/**",
  "**/.venv/**",
  "typeshed/**",
  "tests/test_files/**"
]

site_package_path = [
  ".venv/lib/python3.12/site-packages/"
]

[errors]
#bad-assignment = false
#no-matching-overload = false
#missing-attribute = false
#bad-specialization = false
#bad-argument-type = false
#internal-error = false
# bad-return = false