name: CI

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  typecheck:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Python 3.12
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      # Install Python dependencies and run tests
      - name: Install dependencies and run pytest
        run: |
          python -m venv .venv
          source .venv/bin/activate
          python -m pip install --upgrade pip
          # Install your dependencies; adjust the following lines as needed
          pip install -r requirements.txt
          # persists the venv’s scripts dir
          echo "$GITHUB_WORKSPACE/.venv/bin" >> "$GITHUB_PATH"
          # Run tests
          pytest

      - uses: pre-commit/action@v3.0.1
        with:
          extra_args: --all-files

      # Run Pyrefly type checking
      - name: Typecheck with Pyrefly
        run: pyrefly check    
