name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Python 3.12
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      # Install Python dependencies and run tests
      - name: Install dependencies and run pytest
        run: |
          python -m pip install --upgrade pip
          # Install your dependencies; adjust the following lines as needed
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
          # Run tests
          pytest

      # Set up Node.js (needed for Pyright)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Install Pyright globally using npm
      - name: Install Pyright
        run: npm install -g pyright

      # Run Pyright type checking
      - name: Run Pyright
        run: pyright
