name: Daily Package Data Update

on:
  schedule:
    - cron: '0 13 * * *' # Runs at 8am EST
  workflow_dispatch: # Allows manual triggers

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
      
      - name: Setup SSH Known Hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts
      
      - name: Debug SSH Key
        run: |
          echo "$SSH_PRIVATE_KEY" | tr -d '\n' | head -c 100
          eval `ssh-agent -s`
          ssh-keyscan github.com
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          
      - name: Verify Known Hosts
        run: cat ~/.ssh/known_hosts
          
      - name: Verify SSH Key
        run: |
          echo "$SSH_PRIVATE_KEY" | tr -d '\n' | head -c 100 || true
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          eval `ssh-agent -s`
          ssh-add ~/.ssh/id_rsa
          ssh -T git@github.com || true
          
      - name: Debug SSH
        run: |
          ssh -vT git@github.com || true
          cat ~/.ssh/config || true

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      # Install dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Clone the typeshed repository
      - name: Clone Typeshed Repository
        run: git clone git@github.com:python/typeshed.git

      # Run the main script
      - name: Run Main Script
        run: python main.py 2000 --create-daily

      # Automatically commit and push changes
      - name: Commit and Push Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "add latest data"
          branch: main
